CREATE TABLE Users (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  username NVARCHAR(150) NOT NULL UNIQUE,
  email NVARCHAR(255) NOT NULL UNIQUE,
  passwordHash NVARCHAR(255) NOT NULL,
  role NVARCHAR(50) NOT NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Categories (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  name NVARCHAR(150) NOT NULL,
  slug NVARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE Products (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  name NVARCHAR(255) NOT NULL,
  description NVARCHAR(MAX) NOT NULL,
  composition NVARCHAR(MAX) NULL,
  categoryId UNIQUEIDENTIFIER NOT NULL REFERENCES Categories(id),
  price DECIMAL(10,2) NOT NULL,
  imageUrl NVARCHAR(MAX) NOT NULL,
  isAvailable BIT NOT NULL DEFAULT 1,
  cookingTime INT NOT NULL DEFAULT 0,
  tags NVARCHAR(MAX) NULL,
  sizes NVARCHAR(MAX) NULL,
  addons NVARCHAR(MAX) NULL,
  isPopular BIT NOT NULL DEFAULT 0,
  isNew BIT NOT NULL DEFAULT 0,
  isPromo BIT NOT NULL DEFAULT 0,
  rating INT NOT NULL DEFAULT 0,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Orders (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  userId UNIQUEIDENTIFIER NULL REFERENCES Users(id),
  customerName NVARCHAR(200) NOT NULL,
  email NVARCHAR(255) NULL,
  phone NVARCHAR(50) NOT NULL,
  totalPrice DECIMAL(10,2) NOT NULL,
  status NVARCHAR(50) NOT NULL,
  address NVARCHAR(MAX) NULL,
  comment NVARCHAR(MAX) NULL,
  paymentMethod NVARCHAR(100) NULL,
  deliveryMethod NVARCHAR(100) NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE OrderItems (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  orderId UNIQUEIDENTIFIER NOT NULL REFERENCES Orders(id),
  productId UNIQUEIDENTIFIER NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  selectedSize NVARCHAR(MAX) NULL,
  addons NVARCHAR(MAX) NULL
);

CREATE TABLE Settings (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  siteName NVARCHAR(255) NULL,
  siteDescription NVARCHAR(MAX) NULL,
  address NVARCHAR(255) NULL,
  phone NVARCHAR(100) NULL,
  email NVARCHAR(255) NULL,
  workingHours NVARCHAR(255) NULL,
  createdAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
